from pygame import K_e, K_SPACE, K_c, display, init


# all the setting
LASER_COOLDOWN = 0.2
SHOOTING_KEY = K_e
BRAKE_KEY = K_SPACE
CAMERA_KEY = K_c
INIT_BUMPER_NUM = 1
INIT_TURRET_NUM = 0
INIT_ASTEROID_NUM = 1
STAR_NUM = 300
INIT_BUMPER_SPEED = 1
INIT_TURRET_SHOOTING_SPEED = 2
RENDER_DISTANCE = 800
ASTEROID_SPAWN_TIME = 15
BUMPER_SPAWN_TIME = 10
TURRET_SPAWN_TIME = 20
BUMPER_SPEED_UPDATE_TIME = 30
TURRET_SHOOTING_SPEED_UPDATE_TIME = 20

MAX_ASTEROID = 10
MAX_BUMPER = 20
MAX_TURRET = 10
init()
screen_info = display.Info()
SCREEN_WIDTH, SCREEN_HEIGHT = screen_info.current_w, screen_info.current_h